# NUMPY

NumPy (Numerical Python) is a library for efficient numerical computations.

Provides ndarrays: N-dimensional arrays (faster than Python lists)

Provides mathematical functions to operate on arrays

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Integrates well with Pandas, Matplotlib, SciPy, and machine learning libraries

____________________________________________________________________________________________________


## 🔹 1. Installing and Importing NumPy

pip install numpy

import numpy as np

By convention, NumPy is imported as np.

____________________________________________________________________________________________________

## NumPy Creating Arrays


Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:



### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [18]:
import numpy as np
arr0D = np.array(23)
print(arr0D)
print('total dimensions:',arr0D.ndim)


23
total dimensions: 0


_________________________________________________________________________________________________

### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [14]:
import numpy as np
arr1D = np.array([0,2,4,6,8])
print(arr1D)
print('total dimensions:',arr1D.ndim)


[0 2 4 6 8]
total dimensions: 1


___________________________________________________________________________________________________

### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



In [15]:
import numpy as np
arr2D = np.array([[0,2,4,6,8],[1,3,5,7,9]])
print(arr2D)
print('total dimensions:',arr2D.ndim)


[[0 2 4 6 8]
 [1 3 5 7 9]]
total dimensions: 2


_________________________________________________________________________________________________

### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [17]:
import numpy as np
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print()
print('total dimensions:',arr3D.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

total dimensions: 3


___________________________________________________________________________________________________

### Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [19]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

0
1
2
3


____________________________________________________________________________________________________

### Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [24]:
import numpy as np
arrh = np.array([1,2,3,4],ndmin=4)
print(arrh)
print('no.of dimensions:',arrh.ndim)

[[[[1 2 3 4]]]]
no.of dimensions: 4


_________________________________________________________________________________________________

### Access Array Elements
#### Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [27]:
# Accessing 1D array
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1[2])

3


_________________________________________________________________________________________________

### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [31]:
# Accessing 2D array
import numpy as np
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print('first row, second element: ',arr2[0,1])

[[1 2 3 4]
 [5 6 7 8]]
first row, second element:  2


_________________________________________________________________________________________________

### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [35]:
# Accessing 3D array
import numpy as np
arr3 = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
    ])
print(arr3)
print('first array, second row, third element: ',arr3[0,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
first array, second row, third element:  7


__________________________________________________________________________________________________

### Negative Indexing
Use negative indexing to access an array from the end.

In [3]:
import numpy as np
arrNI = np.array([[1,2,3,4],[5,6,7,8]])
print(arrNI)
print('last element from second array:',arrNI[1,-1])

[[1 2 3 4]
 [5 6 7 8]]
last element from second array: 8


___________________________________________________________________________________________________________________________________________

### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Works for 1D, 2D, 3D, and higher-dimensional arrays

In [6]:
import numpy as np
arrSlice = np.array([1,2,3,4,5,6,7])
print(arrSlice)
print('after slicing:',arrSlice[1:4])

[1 2 3 4 5 6 7]
after slicing: [2 3 4]


#### Slicing 2D Arrays

For 2D arrays, you specify row slice first, then column slice:

In [16]:
import numpy as np
arrSlice2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# accessing single row
print('accessing single row:',arrSlice2[0])   

# Accessing a Single Column
# Columns are accessed by all rows, specific column: 
# : → means all rows
# 0,1,2 → column index
print('accessing single column:',arrSlice2[:,1])

# Accessing Specific Element
print('accessing specific element:',arrSlice2[1,2])   # row 2, column 3

accessing single row: [1 2 3]
accessing single column: [2 5 8]
accessing specific element: 6


___________________________________________________________________________________________________________________________________________

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

#### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


___________________________________________________________________________________________________________________________________________

### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

A non integer string like 'a' can not be converted to integer (will raise an error):



In [8]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype='S')  #Coverting data type from interger to string
print(arr)
print(arr.dtype)
newarr = np.array([2.3,4.9,5.6],dtype='i')
print(newarr)
print(newarr.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1
[2 4 5]
int32


In [ ]:
# For i, u, f, S and U we can define size as well.
# Create an array with data type 4 bytes integer:

import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(arr1.dtype)
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)


[1 2 3 4]
int64
[1 2 3 4]
int32


___________________________________________________________________________________________________________________________________________

### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [16]:
import numpy as np
arr  = np.array([1,2.6,3.2,4.0])
print(arr)
print(arr.dtype)
new_arr = arr.astype('i')  #making it interger while copying the array
print(new_arr)
print(new_arr.dtype)

[1.  2.6 3.2 4. ]
float64
[1 2 3 4]
int32


In [20]:
# Change data type from integer to boolean:
import numpy as np
arr=np.array([2,0,4,0])
print(arr)
print(arr.dtype)
newarr = arr.astype(bool)  # making it boolean
#  we can also use  newarr = arr.astype('b')  # making it boolean
print(newarr)
print(newarr.dtype)


[2 0 4 0]
int64
[ True False  True False]
bool


__________________________________________________________________________________________________________________________________________

### NumPy Array Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### COPY:
uses the copy() function to create a copy of the array.

The copy SHOULD NOT be affected by the changes made to the original array.



In [2]:
import numpy as np
arr = np.array([1,3,5,7])
new_arr = arr.copy()
arr[0]=20
print('original array:',arr)
print('copided array:',new_arr)

original array: [20  3  5  7]
copided array: [1 3 5 7]


#### VIEW:
We use view() function to create a view.

The view SHOULD be affected by the changes made to the original array.


In [3]:
import numpy as np
arr=np.array([23,45,67,43])
x=arr.view()
arr[1]=18
print('original array:',arr)
print('viewed array:',x)

original array: [23 18 67 43]
viewed array: [23 18 67 43]


In [7]:
# Make Changes in the VIEW:
# Make a view, change the view, and display both arrays:
import numpy as np
arr=np.array([21,34,56,49])
x=arr.view()
x[1]=19
print('original array:',arr)
print('viewed array:',x)    #The original array SHOULD be affected by the changes made to the view.

original array: [21 19 56 49]
viewed array: [21 19 56 49]


#### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [8]:
import numpy as np
arr=np.array([2,3,4,5,6])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[2 3 4 5 6]


___________________________________________________________________________________________________________________________________________

### Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array :
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

arr.shape tells you how many rows and no.of elements it has.

In [ ]:
import numpy as np
arr=np.array([[1,3,4,7],[2,5,6,8]])
print(arr)
print('the shape of array:',arr.shape)  #eturns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

[[1 3 4 7]
 [2 5 6 8]]
the shape of array: (2, 4)


In [12]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


___________________________________________________________________________________________________________________________________________

### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

##### Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

##### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
new_arr=arr.reshape(4,3)  #it consists of 4 arrays(rows) and each array has 3 elements
print(new_arr)
print()
new_arr1= arr.reshape(3,4)
print(new_arr1)                  #it consists of 3 arrays(rows) and each array has 4 elements

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #it consists of 2 arrays(rows) and each array has 3 arrays and each array has 2 elements
new_arr=arr.reshape(2,3,2) 
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#  you do not have to specify an exact number for one of the dimensions in the reshape method.
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr= arr.reshape(2, 2, -1)  #we can use -1 to reshape into any dimension
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
new_arr=arr.reshape(-1)
print(new_arr)
print()
new_arr1=arr.flatten()  #it is also used to convert multi-dimensional array into one-dimensional array
print(new_arr1)

[1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8]


__________________________________________________________________________________________________________________________________________

### NumPy Array Iterating
terating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a n-D array it will go through n-1th dimension one by one.

In [ ]:
# 1D array
# If we iterate on a 1-D array it will go through each element one by one.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [28]:
#2D array
import numpy as np
arr=np.array([[1,3,5,7],[2,4,6,8]])
for i in arr:
    print(i)


[1 3 5 7]
[2 4 6 8]


In [29]:

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
import numpy as np
arr=np.array([[1,3,5,7],[2,4,6,8]])
for j in arr:
    for k in j:
        print(k)

1
3
5
7
2
4
6
8


In [ ]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    print(i)    #it will print the 2-D arrays


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [32]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration
##### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr):       #with this we can iterate through all the scalar elements of an array without using inner loops
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):        #converts the data type of the elements while iterating through them
    print(i)
print(i.dtype)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
|S21


#### Iterating With Different Step Size
We can use filtering and followed by iteration.

In [38]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.nditer(arr[:,::2]):   #here we are selecting all rows, then selecting all columns with a step of 2
    print(i)

1
3
5
7


### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.



In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
for id, i in np.ndenumerate(arr):   #here it will print the index and the value of the array where the index starts from 0
    print(id, i)

(0,) 1
(1,) 3
(2,) 5
(3,) 7
(4,) 9


__________________________________________________________________________________________________________________________________________

## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [49]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [59]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


#### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [61]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.stack((arr1,arr2),axis=1)      #this weill stack the arrays on top of each other(makes the array accross the column )
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


#### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [64]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.hstack((arr1,arr2))   #this will stack the arrays horizontally(makes the array accross the row )
print(arr)

[1 2 3 4 5 6 7 8]


#### Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.vstack((arr1,arr2))  #this will stack the arrays vertically(makes the array accross the column )
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


#### Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [67]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.dstack((arr1,arr2))   #this will stack the arrays depth wise(makes the array accross the height )
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


___________________________________________________________________________________________________________________________________________

## Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

Note: The return value is a list containing three arrays.

If the array has less elements than required, it will adjust from the end accordingly.

Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting, array_split() worked properly but split() would fail.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
new_arr=np.array_split(arr,3)
print(new_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [ ]:
# Split Into Arrays
# The return value of the array_split() method is a list containing each of the split as an array.
# If you split an array into 3 arrays, you can access them from the result just like any array element:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=np.array_split(arr,3)
print(new_arr[0])        #accessing the splitted arrays
print(new_arr[1])
print(new_arr[2])

[1 2]
[3 4]
[5 6]


##### Splitting 2-D Arrays

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [8]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new_arr = np.array_split(arr, 3)
print(new_arr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [9]:
# Split the 2-D array into three 2-D arrays along columns.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
new_arr = np.array_split(arr, 3,axis=1)
print(new_arr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


_________________________________________________________________________________________________________________________________________________

## Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
# Find the indexes where the value is 4:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x=np.where(arr == 4)
print(x)      # the value 4 is present at index 3, 5 and 6.



(array([3, 5, 6]),)


In [12]:
# Find the indexes where the values are even:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 7, 6])
x=np.where(arr%2 == 0)
print(x)


(array([1, 3, 6]),)


#### Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.



In [ ]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x=np.searchsorted(arr,8)
print(x)    #it will return the index where 8 should be inserted to maintain the searchsorted order


2


In [16]:
# Multiple Values
# To search for more than one value, use an array with the specified values.
#Find the indexes where the values 2, 4, and 6 should be inserted:
import numpy as np
arr = np.array([1, 3, 5, 7])
x=np.searchsorted(arr,[2,4,6])
print(x)


[1 2 3]


_________________________________________________________________________________________________________________________________________________

## Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

Note: This method returns a copy of the array, leaving the original array unchanged.



In [18]:
import numpy as np
arr=np.array([1,6,3,7,2])
new_arr=np.sort(arr)
print('sorted array:',new_arr)

sorted array: [1 2 3 6 7]


In [19]:
# Sort the array alphabetically:

import numpy as np
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [20]:
# Sort a boolean array:

import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [22]:
# Sort a 2-D array:

import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])   #it will sort the array row wise
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


________________________________________________________________________________________________________________________________________________

## Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [24]:
import numpy as np
arr=np.array([2,7,4,9])
x=[True, False, False,True]
new_arr=arr[x]
print(new_arr)

[2 9]


#### Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [ ]:
import numpy as np
arr=np.array([42,36,98,76,23])
filtered_arr = []
for i in arr:
    if i>40:
        filtered_arr.append(True)
    else:
        filtered_arr.append(False)
new_arr=arr[filtered_arr]
print('filterd array:',new_arr) #return values that are greater than 40


filterd array: [42 98 76]


#### Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [28]:
import numpy as np
arr=np.array([43,27,89,34,62])
x=arr>40
new_arr=arr[x]
print(new_arr)

[43 89 62]


_________________________________________________________________________________________________________________

### Random Numbers in NumPy


Random numbers generated through a generation algorithm are called pseudo random.

#### Generate Random Number
NumPy offers the random module to work with random numbers.



In [2]:
from numpy import random
x = random.randint(100)
print('the random no. is :',x)

the random no. is : 44


#### Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [2]:
from numpy import random
x=random.rand()
print(x)

0.3312850123619475


### Generate Random Array

Integers

The randint() method takes a size parameter where you can specify the shape of an array.

In [ ]:
# Generate 1D array with 5 elements
from numpy import random
x = random.randint(100, size=(5))
print(x)

[41 71 43 32  3]


In [6]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
from numpy import random
y=random.randint(100, size=(3,5))
print(y)


[[36 16 34 24 16]
 [90 42 10 45 92]
 [23 16 34  6 40]]


Floats

The rand() method also allows you to specify the shape of the array.

In [8]:
# Generate 1D array with 5 elements in float vallues
from numpy import random
x=random.rand(5)
print(x)


[0.3827694  0.50694026 0.84174314 0.75391432 0.70645426]


In [9]:
# Generate a 2-D array with 3 rows, each row containing 5 random float values
from numpy import random
y=random.rand(3,5)
print(y)


[[0.10691461 0.76273357 0.49872265 0.94630171 0.54801204]
 [0.03388039 0.2701934  0.92192786 0.05540864 0.31209436]
 [0.40099274 0.22264724 0.66292447 0.98779111 0.59450239]]


#### Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [11]:
from numpy import random
a=random.choice([1,3,5,7,9])
print(a)

3


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [ ]:
from numpy import random
x=random.choice([1,3,5,7,9],size=(3,4)) #generates a array with 3 rows and 4 elements from given elements itself
print(x)

[[7 3 5 7]
 [9 1 5 9]
 [1 9 1 7]]


### NumPy Arithmetic Array Operations

NumPy provides a wide range of operations that can perform on arrays, including arithmetic operations

#### List of Arithmetic Operations
Here's a list of various arithmetic operations along with their associated operators and built-in functions:

Element-wise Operation	Operator	Function

Addition	+	add()

Subtraction	-	subtract()

Multiplication	*	multiply()

Division	/	divide()

Exponentiation	**	power()

Modulus	%	mod()

To perform each operation, we can either use the associated operator or built-in functions. 

In [15]:
import numpy as np
arr1=np.array([1,3,5,7])
arr2=np.array([2,4,6,8])
res1=arr1+arr2
print("using + operator",res1)
print()
res2=np.add(arr1,arr2)
print('using add() function',res2)

using + operator [ 3  7 11 15]

using add() function [ 3  7 11 15]


### Common NumPy Array Functions
There are many NumPy array functions available but here are some of the most commonly used ones.

Array Operations	Functions

Array Creation Functions	np.array(), np.zeros(), np.ones(), np.empty(), etc.

Array Manipulation Functions	np.reshape(), np.transpose(), etc.

Array Mathematical Functions	np.add(), np.subtract(), np.sqrt(), np.power(), etc.

Array Statistical Functions	np.median(), np.mean(), np.std(), and np.var().

Array Input and Output Functions	np.save(), np.load(), np.loadtxt(), etc.

In [18]:
# NumPy Array Creation Functions
import numpy as np
arr0=np.zeros((2,3))  #create a 2*3 matrix with all zeros
print(arr0)
arr1=np.ones((2,3))  #create a 2*3 matrix with all ones
print(arr1)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### NumPy Array Statistical Functions
NumPy provides us with various statistical functions to perform statistical data analysis.

These statistical functions are useful to find basic statistical concepts like mean, median, variance, etc. It is also used to find the maximum or the minimum element in an array.

In [21]:
import numpy as np
marks=np.array([82,89,92,78,86])
mean_marks=np.mean(marks)
print('mean fo marks;',mean_marks)
median_marks=np.median(marks)
print('median of marks:',median_marks)
min_marks=np.min(marks)
print("min marks :",min_marks)
max_marks=np.max(marks)
print("max marks :",max_marks)


mean fo marks; 85.4
median of marks: 86.0
min marks : 78
max marks : 92


### NumPy Array Input/Output Functions
NumPy offers several input/output (I/O) functions for loading and saving data to and from files.

In [22]:
import numpy as np
arr=np.array([1,2,4,8])
#save data into a file
np.savetxt('data.txt',arr)
#load data from a file
loaded_data=np.loadtxt('data.txt')
print(loaded_data)

[1. 2. 4. 8.]


### NumPy Comparison Operators
NumPy provides various element-wise comparison operators that can compare the elements of two NumPy arrays.

Here's a list of various comparison operators available in NumPy.

Operators	Descriptions

< (less than)	returns True if element of the first array is less than the second one

<= (less than or equal to)	returns True if element of the first array is less than or equal to the second one

 > (greater than)	returns True if element of the first array is greater than the second one

>= (greater than or equal to)	returns True if element of the first array is greater than or equal to the second one

== (equal to)	returns True if the element of the first array is equal to the second one

!= (not equal to)	returns True if the element of the first array is not equal to the second one


In [23]:
# NumPy Comparison Operators
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])

# less than operator
result1 = array1 < array2
print("array1 < array2:",result1)    # Output: [ True False False]

# greater than operator
result2 = array1 > array2
print("array1 > array2:",result2)    # Output: [False False  True]

# equal to operator
result3 = array1 == array2
print("array1 == array2:",result3)    # Output: [False  True False]

array1 < array2: [ True False False]
array1 > array2: [False False  True]
array1 == array2: [False  True False]


#### NumPy Comparison Functions
NumPy also provides built-in functions to perform all the comparison operations.

Functions	Descriptions

less()	returns element-wise True if the first value is less than the second

less_equal()	returns element-wise True if the first value is less than or equal to second

greater()	returns element-wise True if the first value is greater then second

greater_equal()	returns element-wise True if the first value is greater than or equal to second

equal()	returns element-wise True if two values are equal

not_equal()	returns element-wise True if two values are not equal

In [24]:
import numpy as np

array1 = np.array([9, 12, 21])
array2 = np.array([21, 12, 9])

# use of less()
result = np.less(array1, array2)
print("Using less():",result)    

# use of less_equal()
result = np.less_equal(array1, array2)
print("Using less_equal():",result)     

# use of greater()
result = np.greater(array1, array2)
print("Using greater():",result)    

# use of greater_equal()
result = np.greater_equal(array1, array2)
print("Using greater_equal():",result)   
# use of equal()
result = np.equal(array1, array2)
print("Using equal():",result)   

# use of not_equal()
result = np.not_equal(array1, array2)
print("Using not_equal():",result)    

Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


________________________________________________________________________________________________________________________________________

### NumPy Math Functions
Numpy provides a wide range of mathematical functions that can be performed on arrays.

Trigonometric Functions

Arithmetic Functions

Rounding Functions

#### Trigonometric Functions
NumPy provides a set of standard trigonometric functions to calculate the trigonometric ratios (sine, cosine, tangent, etc.)

Trigonometric Function	Computes (in radians)

sin()	the sine of an angle    
cos()	cosine of an angle  
tan()	tangent of an angle 
arcsin()	the inverse sine    
arccos()	the inverse cosine  
arctan()	the inverse tangent 
degrees()	converts an angle in radians to degrees 
radians()	converts an angle in degrees to radians 


In [28]:
import numpy as np

# array of angles in radians
angles = np.array([0, 1, 2])
print("Angles:", angles)

# compute the sine of the angles
sine_values = np.sin(angles)
print("Sine values:", sine_values)

tan_values = np.tan(angles)
print("TAN values:", tan_values)



Angles: [0 1 2]
Sine values: [0.         0.84147098 0.90929743]
TAN values: [ 0.          1.55740772 -2.18503986]


In [32]:
import numpy as np

# define an angle in radians
angle =  1.57079633
print("Initial angle in radian:", angle)

# convert the angle to degrees
angle_degree = np.degrees(angle)
print("Angle in degrees:", angle_degree)

# convert the angle back to radians
angle_radian = np.radians(angle_degree)
print("Angle in radians (after conversion):", angle_radian)
##Here, we first initialized an angle in radians. Then we converted it to degrees using the degrees() function.
# Similarly, we used radians() to convert the degrees back to radians.



Initial angle in radian: 1.57079633
Angle in degrees: 90.0000001836389
Angle in radians (after conversion): 1.57079633
