# NUMPY

NumPy (Numerical Python) is a library for efficient numerical computations.

Provides ndarrays: N-dimensional arrays (faster than Python lists)

Provides mathematical functions to operate on arrays

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Integrates well with Pandas, Matplotlib, SciPy, and machine learning libraries

____________________________________________________________________________________________________


## 🔹 1. Installing and Importing NumPy

pip install numpy

import numpy as np

By convention, NumPy is imported as np.

____________________________________________________________________________________________________

## NumPy Creating Arrays


Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:



### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [18]:
import numpy as np
arr0D = np.array(23)
print(arr0D)
print('total dimensions:',arr0D.ndim)


23
total dimensions: 0


_________________________________________________________________________________________________

### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [14]:
import numpy as np
arr1D = np.array([0,2,4,6,8])
print(arr1D)
print('total dimensions:',arr1D.ndim)


[0 2 4 6 8]
total dimensions: 1


___________________________________________________________________________________________________

### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



In [15]:
import numpy as np
arr2D = np.array([[0,2,4,6,8],[1,3,5,7,9]])
print(arr2D)
print('total dimensions:',arr2D.ndim)


[[0 2 4 6 8]
 [1 3 5 7 9]]
total dimensions: 2


_________________________________________________________________________________________________

### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [17]:
import numpy as np
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print()
print('total dimensions:',arr3D.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

total dimensions: 3


___________________________________________________________________________________________________

### Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [19]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

0
1
2
3


____________________________________________________________________________________________________

### Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [24]:
import numpy as np
arrh = np.array([1,2,3,4],ndmin=4)
print(arrh)
print('no.of dimensions:',arrh.ndim)

[[[[1 2 3 4]]]]
no.of dimensions: 4


_________________________________________________________________________________________________

### Access Array Elements
#### Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [27]:
# Accessing 1D array
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1[2])

3


_________________________________________________________________________________________________

### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [31]:
# Accessing 2D array
import numpy as np
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print('first row, second element: ',arr2[0,1])

[[1 2 3 4]
 [5 6 7 8]]
first row, second element:  2


_________________________________________________________________________________________________

### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [35]:
# Accessing 3D array
import numpy as np
arr3 = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
    ])
print(arr3)
print('first array, second row, third element: ',arr3[0,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
first array, second row, third element:  7
