# NUMPY

NumPy (Numerical Python) is a library for efficient numerical computations.

Provides ndarrays: N-dimensional arrays (faster than Python lists)

Provides mathematical functions to operate on arrays

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

Integrates well with Pandas, Matplotlib, SciPy, and machine learning libraries

____________________________________________________________________________________________________


## 🔹 1. Installing and Importing NumPy

pip install numpy

import numpy as np

By convention, NumPy is imported as np.

____________________________________________________________________________________________________

## NumPy Creating Arrays


Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:



### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [18]:
import numpy as np
arr0D = np.array(23)
print(arr0D)
print('total dimensions:',arr0D.ndim)


23
total dimensions: 0


_________________________________________________________________________________________________

### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [14]:
import numpy as np
arr1D = np.array([0,2,4,6,8])
print(arr1D)
print('total dimensions:',arr1D.ndim)


[0 2 4 6 8]
total dimensions: 1


___________________________________________________________________________________________________

### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat



In [15]:
import numpy as np
arr2D = np.array([[0,2,4,6,8],[1,3,5,7,9]])
print(arr2D)
print('total dimensions:',arr2D.ndim)


[[0 2 4 6 8]
 [1 3 5 7 9]]
total dimensions: 2


_________________________________________________________________________________________________

### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [17]:
import numpy as np
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)
print()
print('total dimensions:',arr3D.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

total dimensions: 3


___________________________________________________________________________________________________

### Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [19]:
print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

0
1
2
3


____________________________________________________________________________________________________

### Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [24]:
import numpy as np
arrh = np.array([1,2,3,4],ndmin=4)
print(arrh)
print('no.of dimensions:',arrh.ndim)

[[[[1 2 3 4]]]]
no.of dimensions: 4


_________________________________________________________________________________________________

### Access Array Elements
#### Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [27]:
# Accessing 1D array
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1[2])

3


_________________________________________________________________________________________________

### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [31]:
# Accessing 2D array
import numpy as np
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print('first row, second element: ',arr2[0,1])

[[1 2 3 4]
 [5 6 7 8]]
first row, second element:  2


_________________________________________________________________________________________________

### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [35]:
# Accessing 3D array
import numpy as np
arr3 = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[13,14,15,16]]
    ])
print(arr3)
print('first array, second row, third element: ',arr3[0,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
first array, second row, third element:  7


__________________________________________________________________________________________________

### Negative Indexing
Use negative indexing to access an array from the end.

In [3]:
import numpy as np
arrNI = np.array([[1,2,3,4],[5,6,7,8]])
print(arrNI)
print('last element from second array:',arrNI[1,-1])

[[1 2 3 4]
 [5 6 7 8]]
last element from second array: 8


___________________________________________________________________________________________________________________________________________

### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Works for 1D, 2D, 3D, and higher-dimensional arrays

In [6]:
import numpy as np
arrSlice = np.array([1,2,3,4,5,6,7])
print(arrSlice)
print('after slicing:',arrSlice[1:4])

[1 2 3 4 5 6 7]
after slicing: [2 3 4]


#### Slicing 2D Arrays

For 2D arrays, you specify row slice first, then column slice:

In [16]:
import numpy as np
arrSlice2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# accessing single row
print('accessing single row:',arrSlice2[0])   

# Accessing a Single Column
# Columns are accessed by all rows, specific column: 
# : → means all rows
# 0,1,2 → column index
print('accessing single column:',arrSlice2[:,1])

# Accessing Specific Element
print('accessing specific element:',arrSlice2[1,2])   # row 2, column 3

accessing single row: [1 2 3]
accessing single column: [2 5 8]
accessing specific element: 6


___________________________________________________________________________________________________________________________________________

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

#### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


___________________________________________________________________________________________________________________________________________

### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

A non integer string like 'a' can not be converted to integer (will raise an error):



In [8]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype='S')  #Coverting data type from interger to string
print(arr)
print(arr.dtype)
newarr = np.array([2.3,4.9,5.6],dtype='i')
print(newarr)
print(newarr.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1
[2 4 5]
int32


In [ ]:
# For i, u, f, S and U we can define size as well.
# Create an array with data type 4 bytes integer:

import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(arr1.dtype)
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)


[1 2 3 4]
int64
[1 2 3 4]
int32


___________________________________________________________________________________________________________________________________________

### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [16]:
import numpy as np
arr  = np.array([1,2.6,3.2,4.0])
print(arr)
print(arr.dtype)
new_arr = arr.astype('i')  #making it interger while copying the array
print(new_arr)
print(new_arr.dtype)

[1.  2.6 3.2 4. ]
float64
[1 2 3 4]
int32


In [20]:
# Change data type from integer to boolean:
import numpy as np
arr=np.array([2,0,4,0])
print(arr)
print(arr.dtype)
newarr = arr.astype(bool)  # making it boolean
#  we can also use  newarr = arr.astype('b')  # making it boolean
print(newarr)
print(newarr.dtype)


[2 0 4 0]
int64
[ True False  True False]
bool


__________________________________________________________________________________________________________________________________________

### NumPy Array Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### COPY:
uses the copy() function to create a copy of the array.

The copy SHOULD NOT be affected by the changes made to the original array.



In [2]:
import numpy as np
arr = np.array([1,3,5,7])
new_arr = arr.copy()
arr[0]=20
print('original array:',arr)
print('copided array:',new_arr)

original array: [20  3  5  7]
copided array: [1 3 5 7]


#### VIEW:
We use view() function to create a view.

The view SHOULD be affected by the changes made to the original array.


In [3]:
import numpy as np
arr=np.array([23,45,67,43])
x=arr.view()
arr[1]=18
print('original array:',arr)
print('viewed array:',x)

original array: [23 18 67 43]
viewed array: [23 18 67 43]


In [7]:
# Make Changes in the VIEW:
# Make a view, change the view, and display both arrays:
import numpy as np
arr=np.array([21,34,56,49])
x=arr.view()
x[1]=19
print('original array:',arr)
print('viewed array:',x)    #The original array SHOULD be affected by the changes made to the view.

original array: [21 19 56 49]
viewed array: [21 19 56 49]


#### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [8]:
import numpy as np
arr=np.array([2,3,4,5,6])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[2 3 4 5 6]


___________________________________________________________________________________________________________________________________________

### Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array :
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

arr.shape tells you how many rows and no.of elements it has.

In [ ]:
import numpy as np
arr=np.array([[1,3,4,7],[2,5,6,8]])
print(arr)
print('the shape of array:',arr.shape)  #eturns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

[[1 3 4 7]
 [2 5 6 8]]
the shape of array: (2, 4)


In [12]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


___________________________________________________________________________________________________________________________________________

### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

##### Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

##### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
new_arr=arr.reshape(4,3)  #it consists of 4 arrays(rows) and each array has 3 elements
print(new_arr)
print()
new_arr1= arr.reshape(3,4)
print(new_arr1)                  #it consists of 3 arrays(rows) and each array has 4 elements

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #it consists of 2 arrays(rows) and each array has 3 arrays and each array has 2 elements
new_arr=arr.reshape(2,3,2) 
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#  you do not have to specify an exact number for one of the dimensions in the reshape method.
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr= arr.reshape(2, 2, -1)  #we can use -1 to reshape into any dimension
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
new_arr=arr.reshape(-1)
print(new_arr)
print()
new_arr1=arr.flatten()  #it is also used to convert multi-dimensional array into one-dimensional array
print(new_arr1)

[1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8]


__________________________________________________________________________________________________________________________________________

### NumPy Array Iterating
terating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a n-D array it will go through n-1th dimension one by one.

In [ ]:
# 1D array
# If we iterate on a 1-D array it will go through each element one by one.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


In [28]:
#2D array
import numpy as np
arr=np.array([[1,3,5,7],[2,4,6,8]])
for i in arr:
    print(i)


[1 3 5 7]
[2 4 6 8]


In [29]:

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
import numpy as np
arr=np.array([[1,3,5,7],[2,4,6,8]])
for j in arr:
    for k in j:
        print(k)

1
3
5
7
2
4
6
8


In [ ]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    print(i)    #it will print the 2-D arrays


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [32]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.

import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration
##### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr):       #with this we can iterate through all the scalar elements of an array without using inner loops
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):        #converts the data type of the elements while iterating through them
    print(i)
print(i.dtype)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
|S21


#### Iterating With Different Step Size
We can use filtering and followed by iteration.

In [38]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.nditer(arr[:,::2]):   #here we are selecting all rows, then selecting all columns with a step of 2
    print(i)

1
3
5
7


### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.



In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
for id, i in np.ndenumerate(arr):   #here it will print the index and the value of the array where the index starts from 0
    print(id, i)

(0,) 1
(1,) 3
(2,) 5
(3,) 7
(4,) 9


__________________________________________________________________________________________________________________________________________

## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [49]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [59]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


#### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [61]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.stack((arr1,arr2),axis=1)      #this weill stack the arrays on top of each other(makes the array accross the column )
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


#### Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [64]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.hstack((arr1,arr2))   #this will stack the arrays horizontally(makes the array accross the row )
print(arr)

[1 2 3 4 5 6 7 8]


#### Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.vstack((arr1,arr2))  #this will stack the arrays vertically(makes the array accross the column )
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


#### Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [67]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.dstack((arr1,arr2))   #this will stack the arrays depth wise(makes the array accross the height )
print(arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
